artifacts_root: artifacts


# data_ingestion:
#   root_dir: artifacts/data_ingestion
#   source_URL: "https://github.com/shirish1357/Datasets/raw/main/samsumdata.zip"
#   local_data_file: artifacts/data_ingestion/data.zip
#   unzip_dir: artifacts/data_ingestion


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: ""  # Leave empty since no download is needed
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

